### ISSUE TITLE
Devis : Impossible de saisir le n°Client sans les zéros

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#13]
Thomas avait ajouté un bout de spécifique pour permettre de saisir des n° de Tiers sans les zéros devant à plusieurs endroits.

**Comment by SylvieP** [comment]
Je n'arrive plus à retrouver le bout de spécifique qui se chargeait de rajouter les zéros après la Saisie, mais je continue de chercher...

Les différents endroits sont : 
Entête Devis, Entête Commande, 
Objet Client, Objet Founrisseur, Objet Tiers
Saisie des Réglements Clients

**Comment by CharlesdeLacenne** [comment]
Le contrôle ZBPCORD a été remis sur le type de données BPC, puis le dictionnaire a été validé.
La saisie des codes clients peut donc se faire sans saisir les zéros sur l'ensemble des documents des ventes

**Comment by SylvieP** [comment]
C'est noté.
Il doit y avoir la même chose au niveau des documents Fournisseurs.
Ca aide beaucoup la Comptabilité de pouvoir saisir les n° de Tiers sans les zéros devant.
