### ISSUE TITLE
Demandes d'Achat : Erreur lors de la conversion en Commande Achat

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#19]
Voir capture

**Comment by SylvieP** [comment]
![conversion da en commande](https://cloud.githubusercontent.com/assets/26199775/25332619/69c9edae-28e7-11e7-8758-213ecb6b5403.png)

**Comment by CharlesdeLacenne** [comment]
C'est corrigé. Vous pouvez retester, svp.

**Comment by SylvieP** [comment]
C'était quoi ?

**Comment by CharlesdeLacenne** [comment]
Encore la zone ZPOHTYP dans l’écran POI1 qui n’était pas dans le bon bloc
Et nous avions un point d'entrée sur le trt TRTACHPOH1

**Comment by SylvieP** [comment]
Résolu. Testé.
