### ISSUE TITLE
Plan de Préparation : Erreur tableau plein

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#24]
Une erreur se produit au lancement du traitement Plan de Préparation.
Je ne suis pas complétement sure de la façon dont on utilise le Plan de Préparation mais je vais me renseigner.

![plan de preparation](https://cloud.githubusercontent.com/assets/26199775/25332819/3e58985e-28e8-11e7-8219-798280ee6942.png)

**Comment by CharlesdeLacenne** [comment]
o	Le code activité SLP est dimensionné à 500, alors que sur le dossier actuel, il est à 1000. La mise à jour a repris une valeur par défaut pour ce code activité.
o	Le code activité a été passé à 1000, puis validation du dictionnaire pour ce code activité.
o	Cette opération sera à renouveler, suite à la migration en prod

**Comment by SylvieP** [comment]
Résolu
