### ISSUE TITLE
Statistiques : Déclencheurs Statistiques Absents

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#25]
Les Paramètres Statistiques X3 sont bien présentes mais les Déclencheurs ne sont pas listés.
Il suffit de rappeler les Déclencheurs puis de les enregistrer.

**Comment by CharlesdeLacenne** [comment]
Il n'y avait qu'un déclencheur statistique BAP. Il a été recréé.
Ce point peut etre fermé ?

**Comment by SylvieP** [comment]
Résolu.
