### ISSUE TITLE
Suivi de Fabrication : Impossible d'entrer dans la fonction

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#27]
Voir captures
![suivi fabrication 1](https://cloud.githubusercontent.com/assets/26199775/25336967/1da3bb0e-28fa-11e7-8961-7e291280a484.png)
![suivi fabrication 2](https://cloud.githubusercontent.com/assets/26199775/25336968/1efdd782-28fa-11e7-9b43-cc8ea0329631.png)
![suivi fabrication 3](https://cloud.githubusercontent.com/assets/26199775/25336972/204013ee-28fa-11e7-8f34-957b19179caf.png)

**Comment by CharlesdeLacenne** [comment]
	Correction de l’objet « MFG », onglet « environnement » : ajout des index, expression et code activité : ligne 5, 9 et 12
	Validation des transactions actives de suivi de fabrication
	Test de validation d’accès à la fonction : OK

**Comment by SylvieP** [comment]
Résolu.

**Comment by SylvieP** [comment]
Ce problème se produit sur le serveur de Production.
Les explications ne sont pas assez détaillées (quels indexes ? quelle expression ?) pour que je reproduise la solution.

**Comment by SylvieP** [comment]
Résolu
