### ISSUE TITLE
Production : Postes de Charge

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#29]
Erreur lors de l'affichage d'un Poste de Charge.
Voir Capture.
![postes de charge](https://cloud.githubusercontent.com/assets/26199775/25347535/8b9148ea-291b-11e7-8d98-4fc15ddda863.png)

**Comment by CharlesdeLacenne** [comment]
o	Le code activité X13 a été enlevé du bloc 2 de l'écran MWS1 auquel appartient le champ JOURS1.
o	Validation de l’écran MWS1
o	Test d’accès à la fonction : OK

**Comment by SylvieP** [comment]
Testé. Résolu.
