### ISSUE TITLE
Représentations : Impossible de modifier une Représentation

### ISSUE THREAD

**Issue by remyfv-baret** [SylvieP/bookish-carnival#30]
j'ai créé une classe et une représentation ZAPT hier sur le serveur test, qui fonctionnent normalement et renvoient les données qui m'intéréssaient, mais je ne peux plus modifier aucune représentation depuis, avec aucun compte...

le message d'erreur me dit "Vous n'avez accés à cette fiche qu'en consultation".

**Comment by SylvieP** [comment]
Clôture temporaire.

**Comment by SylvieP** [comment]
Nous devons arriver à gérer les représentations correctement pour pouvoir développer des améliorations.
Le ticket est rouvert.

**Comment by SylvieP** [comment]
Le problème a été identifié.
Le type de certaines Représentations, on ne sait pas trop pourquoi, passe en Système (un flag est activé) ce qui interdit la modification.
La modification du flag dans la table rend les modifications à nouveau possibles.
