### ISSUE TITLE
Comptabilité Tiers : Validation Bordereau de Remise impossible

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#31]
Impossible de valider un Bordereau de Remise, un message d'erreur fait référence à un Type de Pièce inexistant.

Voir capture.
![validation bordereau remise](https://cloud.githubusercontent.com/assets/26199775/25432768/10a32ace-2a86-11e7-8596-774d5ceb46f8.png)

**Comment by CharlesdeLacenne** [comment]
	La table contenant les formules de législation contient des types de pièces « ENCAI » ou «DECAI » en lieu et place de « ENC » et « DEC ». Il y a eu un transcodage entre les 2 versions, non géré par la migration. Il faut modifier toutes les formules contenant ces infos.
	Modification des formules contenant ENCAI et DECAI, mais aussi des formules qui donnent des types de pièces transcodées entre  :
	ODDIV en ODG
	ODINV en ODI
	ODDI2 EN ODI
	……
	Export de la table TABFOR afin de la réintégrer après migration, pour éviter de refaire cette manip.
	Test de validation du bordereau : OK

**Comment by SylvieP** [comment]
Résolu

**Comment by SylvieP** [comment]
Ce problème a ressurgi sur le serveur de Production.
C'est très urgent.

**Comment by CharlesdeLacenne** [comment]
L'oubli a été réparé.
Vous pouvez demander aux utilisateurs de refaire le test.

**Comment by SylvieP** [comment]
Testé. Résolu.
