### ISSUE TITLE
Devis : Transformation en Commande

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#32]
Lors de la transformation d'un Devis en Commande, le type de Commande par défaut 'SON' est utilisé alors que nous n'avons qu'un type de Commande de Ventes par défaut : NOR.

Voir Capture.
![transformer un devis en commande](https://cloud.githubusercontent.com/assets/26199775/25445650/3b0a106a-2aaf-11e7-9b63-a5c096ed15ec.png)

**Comment by CharlesdeLacenne** [comment]
o	Il y a des nouvelles valeurs paramètres en Update 9.
o	La valeur paramètre SOHTYPNOR dans le groupe ORD (chapitre Ventes) contient la valeur par défaut SON. Cette valeur a été changée en NOR.
o	Cette opération sera à renouveler, suite à la migration en prod

**Comment by SylvieP** [comment]
Testé. Résolu.
