### ISSUE TITLE
Table Diverse : La table des Marques (Table Diverse 1900) n'est pas présente

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#33]
Impossible de continuer à tester le Formulaire de Création Articles car la table diverse des Marques n'est pas présente.
![table diverse marques](https://cloud.githubusercontent.com/assets/26199775/25491831/698a2746-2b71-11e7-9eba-961fa6782448.png)

**Comment by CharlesdeLacenne** [comment]
	La définition de la table 1900 a été créée dans le dossier de Test.
	Un format d’import/export de la table ATABDIV a été créé dans le dossier de Prod et dans le dossier de Test, afin de pouvoir récupérer les données.
	Export puis Import des 732 fiches de la table diverse 1900
Cette manip sera à refaire pour la bascule si nous ne trouvons pas d'ici là pourquoi cette table diverse n'a pas été migrée.

**Comment by SylvieP** [comment]
Résolu
