### ISSUE TITLE
Plan de Regroupement : Impossible de lancer la Fonction Plan de Regroupement (FUNMPICKA)

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#35]
Voir les captures ci-dessous
![regroupement 0](https://cloud.githubusercontent.com/assets/26199775/25711014/3549e174-30ee-11e7-9ed4-831f5993f84f.png)
![regroupement 1](https://cloud.githubusercontent.com/assets/26199775/25711020/3719ee4a-30ee-11e7-8c23-dd752d57828e.png)
![regroupement 2](https://cloud.githubusercontent.com/assets/26199775/25711022/3898b1de-30ee-11e7-9a39-73ab10d73ff0.png)
![regroupement 3](https://cloud.githubusercontent.com/assets/26199775/25711025/3a64c0d4-30ee-11e7-9e89-29509c1460cf.png)

**Comment by SylvieP** [comment]
Mêmes erreurs si on utilise le bouton **[Regroupement]** présent dans la Fonction **Plan de Travail** (FUNDEBENCHA)
![regroupement 4](https://cloud.githubusercontent.com/assets/26199775/25711333/f1d81f72-30ee-11e7-82a6-b657d5fd3bfc.png)

**Comment by CharlesdeLacenne** [comment]
	Modification dans l’écran MFGPICKA, le champ ZPOHTYPE a une dimension égale à 51. La dimension a été passée à 1.
	Validation de l’écran, de la fenêtre et de la transaction « Acheteur »
	Test d’accès à la fonction : OK

**Comment by SylvieP** [comment]
Résolu.
