### ISSUE TITLE
Plan de l'Acheteur : Impossible de lancer la Fonction Plan de l'Acheteur (GESPOI)

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#36]
Voir Capture
![plan acheteur](https://cloud.githubusercontent.com/assets/26199775/25711946/87565374-30f0-11e7-85b0-d9a120cfd0fc.png)

**Comment by CharlesdeLacenne** [comment]
	Validation de l’objet et de la transaction
	Test de lancement de la fonction : OK

**Comment by SylvieP** [comment]
Résolu.
