### ISSUE TITLE
Commande Vente : Rien ne se charge dans le Tiroir Derniers lus

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#37]
Voir capture
![dernierslus](https://cloud.githubusercontent.com/assets/26199775/25714696/1e34b26a-30f9-11e7-884b-d17c3883631d.png)

**Comment by CharlesdeLacenne** [comment]
	Validation de l’objet SOH
	Test dans la fonction SOH, les derniers lus se chargent bien.

**Comment by SylvieP** [comment]
Résolu.
