### ISSUE TITLE
Facture Interco : La Fonction spécifique (YISSDHSIH) n'est pas disponible 

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#38]
La Fonction spécifique Facture Interco n'est pas présente dans le Menu Ventes | Factures
voir capture x3v7
![factureinterco](https://cloud.githubusercontent.com/assets/26199775/25715633/7153e760-30fc-11e7-8755-e49b56c5e054.png)

**Comment by CharlesdeLacenne** [comment]
Création de l'entrée de menu YISSDHSIH dans Administration\Personnalisation\Pages\Entrées de menu, en associant la fonction YISSDHSIH

**Comment by SylvieP** [comment]
Résolu.
Cette fonction là, je la vois. Bizarre.

<img width="1276" alt="fonction specifique factures interco" src="https://cloud.githubusercontent.com/assets/26199775/25994807/aa69bade-370f-11e7-9fc5-c5006bb9bac1.png">

**Comment by SylvieP** [comment]
Un erreur est apparue dans la trace du traitement Factures InterCo.
On a le temps pour la traiter car nous n'aurons pas besoin de cette fonction avant la fin du mois.

[Trace Factures InterCo.pdf](https://github.com/SylvieP/bookish-carnival/files/995821/Trace.Factures.InterCo.pdf)
