### ISSUE TITLE
Devis et Commande : Erreur "le site n'est pas sur la même société juridique"

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#42]
A la création d'un Devis ou d'une Commande de Vente, si le site d'expédition n'est pas dans la même société que le site vente, un message d'erreur apparait.

![site pas sur la meme societe juridique](https://cloud.githubusercontent.com/assets/26199775/26059819/57d804b2-3983-11e7-87bb-d47f1d6a4e4e.png)

**Comment by CharlesdeLacenne** [comment]
On n'arrive pas à reproduire le souci. Vous pouvez nous donner un exemple concret où ca ne marche pas, svp.

**Comment by SylvieP** [comment]
Saisissez un Devis avec Site de Vente STE et Client 0000013917 sur L01 'site expé=VIL par défaut), par exemple.

**Comment by CharlesdeLacenne** [comment]
Le message apparaît quand, à l'enregistrement du devis ?
Parce qu'en tapant le client, il n'y a pas de souci.
![deviscreat](https://cloud.githubusercontent.com/assets/28091547/26065349/e5380572-3993-11e7-9384-447756841b7e.JPG)

**Comment by SylvieP** [comment]
C'est à l'enregistrement du Devis, voire au changement d'onglet.

**Comment by SylvieP** [comment]
Alexandre a réglé le problème.
Testé. Résolu.
