### ISSUE TITLE
Devis : Problèmes de compteurs 

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#43]
Des problèmes de compteur restant vides sur les sites distants comme VIL et STE.
![compteur devis](https://cloud.githubusercontent.com/assets/26199775/26065019/f3710a40-3992-11e7-8e6a-6810f6127276.png)

**Comment by SylvieP** [comment]
Le premier Devis que j'ai créé hier a pris le numéro **DEV1705VEN-0001** alors qu'on est au début du mois.
Voir mon mail d'hier vers 19h.
A priori les utilisateurs arrivent à saisir et enregistrer un vrai n° de Devis mais en manuel. Bizarre.

**Comment by SylvieP** [comment]
En quittant complètement X3 et en se reconnectant, le compteur peut fonctionner, mais ça ne marche pas à tous les coups.

**Comment by SylvieP** [comment]
Ne réussissant pas a reproduire le problème moi-même, j'ai pu capturer une erreur et une trace sur le PC d'un utilisateur.

![compteur commande 1](https://cloud.githubusercontent.com/assets/26199775/26106699/f9dbe580-3a46-11e7-80a0-107bdd78f694.png)
![compteur commande 2](https://cloud.githubusercontent.com/assets/26199775/26106702/fb9d003e-3a46-11e7-9608-757cfe29e9c6.png)

En sortant de la fonction et en répétant la saisie, une nouvelle NOR a été créée.

**Comment by CharlesdeLacenne** [comment]
Ce doit etre 2 problèmes différents. Pour les devis, on devrait peut etre essayer de remettre par défaut le type de devis SQN. Peut etre que le fait de ne pas mettre de type de devis perturbe parfois le compteur.
Je n'ai pas réussi à reproduire ce problème sur le serveur de test.

Pour les commandes, je pense que c'est autre chose qu'un problème de compteur.

**Comment by SylvieP** [comment]
J'ai fait quelques tests sur les Devis et je me suis rendu compte que :

- tous les Devis migrés ont le type **SQN**
- certains Devis créés depuis le démarrage ont le type **SQN** d'autres rien
- le tye de Devis **SQN** a l'option **Compteur manuel** (et on se retrouve avec une Devis portant le numéro RFQ-FRAK !! )
![type devis dev](https://cloud.githubusercontent.com/assets/26199775/26211152/22be0d6e-3bf2-11e7-9009-05285f98e03c.png)

Du coup j'ai créé le **Type de Devis DEV** que j'ai associé avec le Compteur automatique **SQH**.
On saura rapidement si ce changement résoud le problème.

![type devis dev](https://cloud.githubusercontent.com/assets/26199775/26211172/354b60c6-3bf2-11e7-8139-dea9a30bb250.png)

**Comment by SylvieP** [comment]
La valeur du compteur n'était pas bonne pour la société ADIFOR.
Je l'ai corrigée et tout est rentré dans l'ordre.
(En principe, le mois prochain, tout serait rentré dans l'ordre de toute façon) 
Mais il reste le problème sur les Commandes (un utilisateur vient de m'appeler à ce sujet).
Pour lequel je vais créer un ticket à part de façon à fermer celui des compteurs Devis.

Résolu. Fermeture du ticket et création d'un nouveau ticket pour l'erreur sur la Détermination des taxes.
