### ISSUE TITLE
Règlements Fournisseur : Erreur de dimensionnement Proposition Automatique de Règlement

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#45]
Voir trace
[Erreur Dimensionnement Propo Automatique Règlement.pdf](https://github.com/SylvieP/bookish-carnival/files/1004224/Erreur.Dimensionnement.Propo.Automatique.Reglement.pdf)

**Comment by SylvieP** [comment]
Le problème doit aussi exister côté Client sur les Bordereaux de Remise.
C'était le cas au démarrage de la v7.

**Comment by CharlesdeLacenne** [comment]
J'ai augmenté la dimension dans l'écran de 300 à 1000 lignes.
Vous pouvez demander aux utilisateurs de vérifier, svp

**Comment by SylvieP** [comment]
On ne pourra tester qu'en fin de mois. 
La Compta a procédé de façon à contourner le problème de dimensionnement pour l'échéance du 15.
Je ferme le ticket temporairement.
