### ISSUE TITLE
Ordres de Fabrication : Erreur suite clic sur Clôture/Solde OF

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#48]
Erreur suite clic sur Clôture/Solde OF
Comme au démarrage en 2016, nous retombons sur l'erreur "Fonction non autorisée pour ce site" pour certains utiilsateurs.
THIDA (Logistique Atelier) reçoit le message, je ne le reçois pas en tant qu'Administrateur.

![of fonction non autorisee pour ce site 1](https://cloud.githubusercontent.com/assets/26199775/26115648/e084d5f0-3a60-11e7-9586-6c60db48c357.png)

Si on regarde la variable **GSITE** avec la calculette, que ce soit dans le cas de THIDA ou de SYLPA, elle est égale à "4GF" (4GF est le site principal de la SCI S4G dont seule la comptabilité est gérée dans X3) !!!

![of fonction non autorisee pour ce site 2](https://cloud.githubusercontent.com/assets/26199775/26115649/e2881e3e-3a60-11e7-88d8-23592b20cf8f.png)

**Comment by CharlesdeLacenne** [comment]
Alexandre recherche les modifications qu'il avait faites à l'époque sur ce souci. Ca date de la fin du mois de Mars 2016.

**Comment by AlexandreBrancas** [comment]
Bonjour,
J'ai utilisé profil menu LOGI & profil fonction LOG, sur l'utilisateur HLAC. 
et on arrive à accéder aux différentes fonctions.
Pouvez-vous tester avec l'utilisateur THIDA.
Et si vous avez encore l'erreur, pouvez vous me donner le mot de passe de THIDA. Merci

**Comment by SylvieP** [comment]
Je clos l'incident temporairement puisque  nous avons pu tester la fonction **FUNTDUCLO** (Clôture/solde d'OF en série) qui fonctionne très bien.
Dès que j'ai un moment, j'essaierai de clôturer un OF depuis la Gestion des OFs en utilisant la fonction FUNMCLOSE.
