### ISSUE TITLE
Syracuse : Pas de Users ni de Roles

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#5]
Création de SYLPA et REMFA
Voir s'il est possible d'importer ces éléments.

**Comment by CharlesdeLacenne** [comment]
Il faut recréer manuellement l'ensemble des éléments (users, roles, ...) de Syracuse sur le serveur de Test. Puis faire une sauvegarde la base Mongodb qui sera à réintégrer sur le serveur de prod, lors de la bascule.
Cette opération sera faite lors de la semaine du 9 Mai

**Comment by SylvieP** [comment]
Résolu
