### ISSUE TITLE
Ordres de Fabrication : Impossible d'ajouter une opération non prévue

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#50]
Des erreurs se produisent 

![operation non prevue of 1](https://cloud.githubusercontent.com/assets/26199775/26152414/1db25046-3b07-11e7-8af2-f88bff8623a9.png)
![operation non prevue of 2](https://cloud.githubusercontent.com/assets/26199775/26152422/1fa6776a-3b07-11e7-8801-08c84b40dc73.png)
![operation non prevue of 3](https://cloud.githubusercontent.com/assets/26199775/26152424/21129750-3b07-11e7-8e69-62253f358c11.png)

**Comment by CharlesdeLacenne** [comment]
C'est en cours, on ne trouve pas pour le moment.

**Comment by SylvieP** [comment]
Pour information, on a déjà eu ce problème au démarrage en 2016.
JE viens de vous transférer un mail à ce sujet mais on dirait que les captures d'écran sont différentes.

**Comment by SylvieP** [comment]
Pour information
Il semblerait qu'il y ait un lien avec l'incident #52.
Les messages d'erreur font référence au même traitement.

**Comment by AlexandreBrancas** [comment]
Corrigé en #52

**Comment by SylvieP** [comment]
Résolu.
