### ISSUE TITLE
Ordre de Fabrication : Impossible de visualiser le Détail d'une opération (Action MFOFICH)

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#52]
Une erreur se produit lorsqu'on clique sur l'Action Détail Opération

<img width="462" alt="acceder au detail operation of 1" src="https://cloud.githubusercontent.com/assets/26199775/26287679/f0162dce-3e80-11e7-9d51-5a9554f97264.png">

<img width="458" alt="acceder au detail operation of 2" src="https://cloud.githubusercontent.com/assets/26199775/26287680/f2dc377e-3e80-11e7-8886-047c2f7452ac.png">

Après recherches le traitement MFGWINLIB n'est pas présent dans le dossier X3/TRT.

**Comment by AlexandreBrancas** [comment]
Svg de l'écran MFO1 qui avait encore un code activité X01.
récupération de l'écran MFO1 du dossier X3
revalidation de l'écran dans le dossier BARETU9

**Comment by SylvieP** [comment]
Résolu.
