### ISSUE TITLE
Commande Achat : Erreur entrée dans la fonction GESPOH

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#54]
Je sais que je n'aurais pas du travailler sur le serveur de production mais je ne comprends pas ce qu'il s'est passé.
Je travaillais sur le spécifique d'Export des Commandes d'Achats et tout d'un coup, impossible de rentrer dans la fonction de gestion des Commandes d'achat.
J'ai vérifié la Fenêtre, l'Action, le Traitement sur le serveur de Test et tout me semble identique.
J'ai enlevé complètement le spécifique d'Export en supprimant le bouton Exporter (des menus sur la droite), même résultat.
Je ne sais plus quoi faire :(
C'est super urgent. Si on ne peut pas rentrer dans la fonction, mes utilisateurs vont me maudire.

Voici des captures des erreurs rencontrées.
<img width="523" alt="erreur lancement gespoh 1" src="https://cloud.githubusercontent.com/assets/26199775/26609932/b959d58a-45a4-11e7-8e77-e2e9dd565065.png">
<img width="458" alt="erreur lancement gespoh 2" src="https://cloud.githubusercontent.com/assets/26199775/26609933/bbb6c43c-45a4-11e7-876c-3f77dd169ed0.png">
<img width="458" alt="erreur lancement gespoh 3" src="https://cloud.githubusercontent.com/assets/26199775/26609935/beaac3dc-45a4-11e7-9e00-4ed4010494ee.png">
<img width="535" alt="erreur lancement gespoh 4" src="https://cloud.githubusercontent.com/assets/26199775/26609938/c10f197a-45a4-11e7-9826-b9640e71e14a.png">

**Comment by AlexandreBrancas** [comment]
C’est corrigé, j’ai mis à jour le traitement SPEPOH

Dans les traitements SPExxx, nous devons toujours avoir une etiquette $ACTION
_$ACTION
      Case ACTION
         When Default
      Endcase
Return_

**Comment by SylvieP** [comment]
Résolu.
