### ISSUE TITLE
Suivi de Fabrication : Les sorties Matière ne se font pas systématiquement

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#56]
Les Suivis de Fabrication ne font pas les sorties Matières/Composants systématiquement.
C'est aléatoire mais par exemple, sur **OFA1706VEN-1500**, la sortie de l'article **DOSE70040097** n'a pas été faite.
J'ai effectué quelques recherches pour m'apercevoir que cela dure depuis début 2016, lorsqu'on a lancé la v7.
Je joins un tableau des Suivis pour lesquels aucun composant n'a été sorti.

[Suivis de Fabrication sans Sorties de Composants.xlsx](https://github.com/SylvieP/bookish-carnival/files/1101584/Suivis.de.Fabrication.sans.Sorties.de.Composants.xlsx)

Le problème est assez grave vu qu'il fausse notre stock.

**Comment by CharlesdeLacenne** [comment]
Bonjour Sylvie,

Je viens de transmettre ce souci à la hotline.

**Comment by SylvieP** [comment]
Merci Charles.

**Comment by SylvieP** [comment]
Le problème ne s'est pas reproduit.
Je cloture le ticket.
