### ISSUE TITLE
Articles : Formulaire de Création d'Articles non présent (Spécfique Baret)

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#7]
Le Formulaire de Création d'Articles n'est pas présent dans le menu Données de Base | Articles

**Comment by CharlesdeLacenne** [comment]
L'entrée de menu (dans Syracuse) GESZITM a été créée avec l'association de la fonction GESZITM.
Cette fonction spécifique est de nouveau accessible.

**Comment by SylvieP** [comment]
Testé. Résolu.
Attention, à la premièr eutilisation du Formulaire, j'ai du activer les Familles de produit (Famille Statistique Article) et la table Diverse des Marques (1900) n'est pas présente dans le dossier.

**Comment by SylvieP** [comment]
Je ne vois pas l'entrée de menu. Bizarre.

<img width="1222" alt="formulaire creation articles non present" src="https://cloud.githubusercontent.com/assets/26199775/25993932/1a4df774-370c-11e7-8ec5-8430ef9f2659.png">

**Comment by CharlesdeLacenne** [comment]
![formart](https://cloud.githubusercontent.com/assets/28091547/25994342/d2a0db56-370d-11e7-86d9-2cad471a798d.JPG)

Je la vois pourtant, c'est bizarre

**Comment by SylvieP** [comment]
C'est étrange en effet.
Surtout que j'ai l'impression de l'avoir vu cette fonction sur le serveur de test.
C'est un incident qui a été réglé rapidement.

(Je suis en Teamviewer sur mon PC, je vais faire tester ça en live par Rémy cet après-midi).

**Comment by SylvieP** [comment]
Il y a une chose qui manque aussi à propos du formulaire de création d'Articles, c'est l'Action qui envoie sur ce fameux Formulaire lorsqu'on est en saisie de Devis.

<img width="760" alt="action formulaire creation articles en saisie de devis" src="https://cloud.githubusercontent.com/assets/26199775/25994663/06c8ad9a-370f-11e7-9cb6-377be70ba028.png">

**Comment by SylvieP** [comment]
Je vois la fonction des Factures interCo mais pas celle du Formulaire de création.

**Comment by SylvieP** [comment]
Rémy a le même souci en direct sur le serveur de test.

**Comment by SylvieP** [comment]
Mais Rémy ne voit pas la fonction des Factures interCo.
C'est très étrange.

**Comment by CharlesdeLacenne** [comment]
C'est ce que je pensais, ca doit dépendre des utilisateurs. Je vais regarder d'où ça vient.

**Comment by CharlesdeLacenne** [comment]
C'est OK pour les 2 fonctions "Facture interco" et "Formulaire création d'article". On voit tout le temps les fonctions maintenant, quel que soit l'utilisateur.
Le bouton spécifique sur les lignes de devis a également été ajouté.

**Comment by SylvieP** [comment]
Merci Charles, je ferme donc le ticket.
