### ISSUE TITLE
Paramétrage : Recherche "Globale" non disponible

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#8]
La Recherche "Globale" (zone en haut à droite des pages, à côté des icônes Accueil et Navigation) n'est pas disponible pour le Dossier (voir Capture).

**Comment by CharlesdeLacenne** [comment]
o	La mise à jour des index de recherche globale a été relancée.
o	La recherche globale fonctionne

**Comment by SylvieP** [comment]
Résolu
