### ISSUE TITLE
Syracuse : Aucune Landing Page Baret

### ISSUE THREAD

**Issue by SylvieP** [SylvieP/bookish-carnival#9]
Les Landing Pages BARET ne sont pas présentes (du au problème de Backup MongoDB)
Faudra-t-il les redéfinir ?

**Comment by CharlesdeLacenne** [comment]
Les landing pages ont été exportées du serveur de prod, puis réimportées sur le serveur de test. Ces données appartiennent à la base Mongodb et concernent Syracuse.
Elles ne seront pas perdues lorsqu'on migrera en prod puisqu'on récupérera la sauvegarde Mongodb

**Comment by SylvieP** [comment]
Testé. Résolu.
